# Generated by Django 4.0.1 on 2022-01-22 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_App', '0004_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='articles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TODO_App.task'),
            preserve_default=False,
        ),
    ]
