# Generated by Django 4.0.1 on 2022-01-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_App', '0005_remove_task_user_user_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='articles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TODO_App.task'),
        ),
    ]
