# Generated by Django 4.0.1 on 2022-01-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_App', '0006_alter_user_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='articles',
            new_name='name_user_articles',
        ),
    ]
