# Generated by Django 4.0.1 on 2022-01-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_App', '0007_rename_articles_user_name_user_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='descrpition',
        ),
    ]
