# Generated by Django 4.0.1 on 2022-01-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_App', '0009_remove_user_name_user_articles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='headline',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
