# Generated by Django 4.0.1 on 2022-01-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_App', '0012_alter_task_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='headline',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
